ARG USERNAME=user
ARG USER_ID=1000

FROM debian:trixie-slim AS minimal-with-user
ARG USERNAME
ARG USER_ID
ENV TMPDIR=/tmp
RUN apt-get update --fix-missing \
  && apt-get install -y locales \
  && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
  && locale-gen \
  && apt-get install -y sudo \
  && groupadd --gid ${USER_ID} ${USERNAME} \
  && useradd --uid ${USER_ID} --gid ${USER_ID} -m ${USERNAME} \
  && chsh --shell /bin/bash ${USERNAME} \
  && echo ${USERNAME} ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/${USERNAME} \
  && chmod 0440 /etc/sudoers.d/${USERNAME} \
  && mkdir -p /appl/firestarr \
  && chown -R ${USERNAME}:${USERNAME} /appl


FROM minimal-with-user AS gcc-cmake-with-user
RUN apt-get update --fix-missing \
  && apt-get install -y --no-install-recommends \
  cmake gcc g++ make ninja-build pkg-config \
  curl zip unzip tar ca-certificates git


FROM gcc-cmake-with-user AS firestarr-dev
ARG USERNAME
ARG VERSION
ENV VERSION=${VERSION}
RUN apt-get update --fix-missing \
  && apt-get install -y --no-install-recommends \
  git time nano less psmisc man bc tmux \
  google-perftools libgoogle-perftools-dev golang-github-google-pprof-dev \
  ssh \
  cmake linux-libc-dev curl zip unzip tar ninja-build \
  gdb valgrind libdwarf-dev libelf-dev libdw-dev linux-perf \
  cmake gcc g++ make clang-tools clang-tidy clang-format
RUN git config --global core.editor "nano"
RUN git config --global core.autocrlf false
WORKDIR /appl/firestarr
USER ${USERNAME}
