cmake_minimum_required(VERSION 3.31.6)

include(CheckCXXCompilerFlag)

if(CPU_TUNE_ONLY)
  set(MARCH "mtune")
else()
  # -mcpu is deprecated on some and required on others
  check_cxx_compiler_flag("-march=${CPU_TARGET}" COMPILER_SUPPORTS_MARCH)
  if(COMPILER_SUPPORTS_MARCH)
    set(MARCH "march")
  else()
    set(MARCH "mcpu")
  endif()
endif()

message("Compiler is ${CMAKE_CXX_COMPILER}")
execute_process(COMMAND ${CMAKE_CXX_COMPILER})
if (WIN32)
  message("Not setting compiler flags so binary works across windows")
else()
  message("Compiler flags for ${MARCH}=${CPU_TARGET} with ${CMAKE_CXX_COMPILER} are:")
  if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    execute_process(COMMAND g++ -${MARCH}=${CPU_TARGET} -Q --help=target)
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    execute_process(COMMAND clang -E - -${MARCH}=${CPU_TARGET} "-###")
  endif()
endif()

if(APPLE)
  check_cxx_compiler_flag(-mno-sve HAVE_NO_SVE)
  if(HAVE_NO_SVE)
    message("Disabling SVE")
    add_compile_options(-mno-sve)
  endif()
endif()

check_cxx_compiler_flag(-mno-avx512f HAVE_NO_AVX512F)
if(HAVE_NO_AVX512F)
  message("Disabling AVX512 because performance is worse and results are wildly different with it on")
  add_compile_options(-mno-avx512f)
endif()
