cmake_minimum_required(VERSION 3.31.6)

include(CheckCXXCompilerFlag)

# unset and check flag so it always shows check
macro (CHECK_FLAG _FLAG _RESULT)
  unset(${_RESULT} CACHE)
  CHECK_CXX_COMPILER_FLAG("${_FLAG}" ${_RESULT})
endmacro ()

if(CPU_TUNE_ONLY)
  set(MARCH "mtune")
else()
  # -mcpu is deprecated on some and required on others
  CHECK_FLAG("-march=${CPU_TARGET}" COMPILER_SUPPORTS_MARCH)
  if(COMPILER_SUPPORTS_MARCH)
    set(MARCH "march")
  else()
    set(MARCH "mcpu")
  endif()
endif()

message("Compiler is ${CMAKE_CXX_COMPILER}")
# execute_process(COMMAND ${CMAKE_CXX_COMPILER})
set(COMPILER_TUNING "")
if (WIN32)
  message("Not setting compiler flags so binary works across windows")
else()
  set(COMPILER_TUNING "-${MARCH}=${CPU_TARGET}")
  # make sure flags work but don't output any files
  CHECK_FLAG(${COMPILER_TUNING} COMPILER_TUNING_WORKED)
  if(NOT COMPILER_TUNING_WORKED)
    message("Failed with COMPILER_TUNING=${COMPILER_TUNING} so not using")
    set(COMPILER_TUNING "")
  elseif(CMAKE_VERBOSE_MAKEFILE)
    message("Compiler flags for ${COMPILER_TUNING} with ${CMAKE_CXX_COMPILER} are:")
    if (CMAKE_CXX_COMPILER_ID MATCHES "GNU")
      execute_process(COMMAND ${CMAKE_CXX_COMPILER} ${COMPILER_TUNING} -Q --help=target)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      execute_process(COMMAND ${CMAKE_CXX_COMPILER} -E - ${COMPILER_TUNING} "-###")
    endif()
  endif()
endif()

CHECK_FLAG(-mno-sve HAVE_NO_SVE)
if(HAVE_NO_SVE)
  message("Disabling SVE")
  set(COMPILER_TUNING -mno-sve ${COMPILER_TUNING})
endif()

CHECK_FLAG(-mno-avx512f HAVE_NO_AVX512F)
if(HAVE_NO_AVX512F)
  message("Disabling AVX512 because performance is worse and results are wildly different with it on")
  set(COMPILER_TUNING -mno-avx512f ${COMPILER_TUNING})
endif()
